# Generated by Django 4.2.4 on 2023-11-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_comment_created_at_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.post'),
            preserve_default=False,
        ),
    ]
