# Generated by Django 4.2.4 on 2023-11-16 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositproducts',
            name='wish_users',
        ),
        migrations.RemoveField(
            model_name='savingproducts',
            name='wish_users',
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='like_users',
            field=models.ManyToManyField(related_name='like_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingproducts',
            name='like_users',
            field=models.ManyToManyField(related_name='like_savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
