# Generated by Django 4.2.4 on 2023-11-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeInfo',
            fields=[
                ('cur_unit', models.TextField(primary_key=True, serialize=False)),
                ('cur_nm', models.TextField()),
                ('deal_bas_r', models.TextField()),
            ],
        ),
    ]
