# Generated by Django 4.2.4 on 2023-11-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeinfo',
            name='TTB',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exchangeinfo',
            name='TTS',
            field=models.TextField(null=True),
        ),
    ]
