# Generated by Django 4.2.4 on 2023-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='img_url',
            field=models.TextField(null=True),
        ),
    ]
